-- Tabela DEPARTMENT
CREATE TABLE DEPARTMENT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL
);

-- Tabela TITLE
CREATE TABLE TITLE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL
);

-- Tabela PROFESSOR
CREATE TABLE PROFESSOR (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    department_id BIGINT,
    title_id BIGINT,
    FOREIGN KEY (department_id) REFERENCES DEPARTMENT(id),
    FOREIGN KEY (title_id) REFERENCES TITLE(id)
);

-- Tabela BUILDING
CREATE TABLE BUILDING (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL
);

-- Tabela ROOM
CREATE TABLE ROOM (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    building_id BIGINT,
    FOREIGN KEY (building_id) REFERENCES BUILDING(id)
);

-- Tabela SUBJECT
CREATE TABLE SUBJECT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL
);

-- Tabela SUBJECT_PREREQUISITE
CREATE TABLE SUBJECT_PREREQUISITE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    subject_id BIGINT NOT NULL,
    prerequisiteid BIGINT NOT NULL,
    FOREIGN KEY (subject_id) REFERENCES SUBJECT(id),
    FOREIGN KEY (prerequisiteid) REFERENCES SUBJECT(id)
);

-- Tabela CLASS
CREATE TABLE CLASS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    subject_id BIGINT NOT NULL,
    professor_id BIGINT NOT NULL,
    class_year INT NOT NULL,
    semester INT NOT NULL,
    code VARCHAR(20),
    FOREIGN KEY (subject_id) REFERENCES SUBJECT(id),
    FOREIGN KEY (professor_id) REFERENCES PROFESSOR(id)
);

-- Tabela CLASS_SCHEDULE
CREATE TABLE CLASS_SCHEDULE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    class_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    FOREIGN KEY (class_id) REFERENCES CLASS(id),
    FOREIGN KEY (room_id) REFERENCES ROOM(id)
);
